project_id = "wkzgjvnpnhyluxvclymh"

[functions.rprx-chat]
verify_jwt = false

[functions.admin-user-actions]
verify_jwt = false

[functions.ghl-sync]
verify_jwt = false

[functions.ghl-webhook]
verify_jwt = false

[functions.sync-knowledge-base]
verify_jwt = false
