
-- Create user guide sections table
CREATE TABLE public.user_guide_sections (
  id text PRIMARY KEY,
  title text NOT NULL,
  body text NOT NULL DEFAULT '',
  sort_order integer NOT NULL DEFAULT 0,
  is_active boolean NOT NULL DEFAULT true,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now()
);

ALTER TABLE public.user_guide_sections ENABLE ROW LEVEL SECURITY;

-- Admins full CRUD
CREATE POLICY "Admins can manage guide sections" ON public.user_guide_sections
  FOR ALL TO authenticated USING (has_role(auth.uid(), 'admin'::app_role));

-- All authenticated users can read (for PDF download)
CREATE POLICY "Authenticated can read guide" ON public.user_guide_sections
  FOR SELECT TO authenticated USING (true);

-- Seed default content
INSERT INTO public.user_guide_sections (id, title, body, sort_order) VALUES
('welcome', 'Welcome to RPRx For Life', E'RPRx For Life is your personal financial wellness platform designed to help you reduce financial pressure across the Four Horsemen of household finance: **Interest (Debt)**, **Taxes**, **Insurance**, and **Education**.\n\nUsing AI-driven insights, personalized strategies, and gamification, RPRx empowers you to take control of your financial future — one actionable step at a time.\n\n**Getting Started:**\n1. Complete the Profile Setup Wizard to share your financial snapshot.\n2. Take the Financial Assessment to identify your primary horseman.\n3. Explore personalized strategies recommended just for you.\n4. Track your progress with points, badges, and streaks.', 1),

('dashboard', 'Your Dashboard', E'The Dashboard is your home base. It provides a quick snapshot of your financial wellness journey.\n\n**Key Cards:**\n- **RPRx Score Card** — Your overall financial wellness score, broken down by each horseman.\n- **Current Focus** — The strategy you''re actively working on.\n- **Daily Check-In** — Log your daily engagement to maintain your streak.\n- **Assessment Summary** — A radar chart showing your scores across all four horsemen.\n- **My Strategies** — Quick access to your active and saved strategies.\n- **Money Leak Estimate** — See how much you could be saving annually.\n\n**Customization:** You can drag and reorder cards on the dashboard by pressing and holding the grip icon (⠿) on each card.', 2),

('wizard', 'Profile Setup Wizard', E'The Profile Setup Wizard collects key financial information to personalize your experience.\n\n**Step 1 — Financial Snapshot:** Enter your monthly income, housing costs, debt payments, insurance premiums, and living expenses.\n\n**Step 2 — Your Situation:** Share your filing status, number of children, and financial goals.\n\n**Step 3 — Retirement Picture:** Provide details about your retirement savings, contributions, and timeline.\n\n**Step 4 — Money Mindset:** Answer questions about your financial stress levels and emergency preparedness.\n\nAll information is securely stored and used solely to generate personalized recommendations. You can update your profile at any time from the Profile page.', 3),

('assessment', 'Financial Assessment', E'The Financial Assessment is a guided questionnaire that evaluates your exposure to the Four Horsemen.\n\n**How It Works:**\n- Answer questions across categories like debt management, tax optimization, insurance coverage, and financial education.\n- Each answer contributes to your horseman scores.\n- At the end, you''ll receive your RPRx Score and your Primary Horseman — the area where you have the most opportunity for improvement.\n\n**Retaking the Assessment:** You can retake the assessment at any time to see how your scores change as you implement strategies. Your assessment history is saved so you can track progress over time.\n\n**Deep Dives:** After completing the assessment, you can take a Deep Dive into any horseman for a more detailed analysis.', 4),

('results', 'Understanding Your Results', E'The Results page breaks down your assessment findings into actionable insights.\n\n**RPRx Score:** Your overall score ranges from 0-100, with a letter grade. Higher scores indicate better financial wellness.\n\n**Horseman Radar Chart:** A visual representation of your scores across all four horsemen, making it easy to spot strengths and weaknesses.\n\n**Primary Horseman:** The area where you scored lowest — this is where RPRx recommends focusing first.\n\n**Quick Wins:** Immediately actionable strategies based on your results.\n\n**Cash Flow Indicator:** Shows whether your monthly cash flow is in surplus, tight, or deficit based on your profile data.\n\n**Diagnostic Feedback:** Personalized commentary on your financial situation with specific recommendations.', 5),

('strategies', 'Strategy Assistant', E'The Strategy Assistant is your AI-powered financial coach.\n\n**How to Use It:**\n- Start a new conversation or continue an existing one.\n- Ask questions about any financial topic — debt reduction, tax strategies, insurance optimization, or education planning.\n- The assistant uses your profile data and assessment results to provide personalized advice.\n\n**Suggested Prompts:** The assistant provides contextual prompt suggestions based on your primary horseman and active strategies.\n\n**Conversations:** All conversations are saved automatically. You can access previous conversations from the sidebar.\n\n**Important:** The Strategy Assistant provides educational information, not financial advice. Always consult with a qualified financial professional before making major financial decisions.', 6),

('plans', 'Your Plans', E'Plans are saved implementation roadmaps for specific financial strategies.\n\n**Creating a Plan:** When you find a strategy you want to implement, save it as a plan. Each plan includes:\n- Step-by-step implementation checklist\n- Estimated impact and complexity rating\n- Requirements and prerequisites\n- Space for personal notes\n\n**Managing Plans:**\n- Mark steps as complete to track your progress.\n- Set a plan as your "Focus Plan" to feature it on your dashboard.\n- Change plan status: Not Started → In Progress → Completed.\n\n**Downloading Plans:** You can download any plan as a PDF or Markdown file for offline reference using the download button on the plan detail page.', 7),

('debt-eliminator', 'Debt Eliminator', E'The Debt Eliminator is a dedicated tool for creating and tracking your debt payoff journey.\n\n**Setup:**\n1. Choose your debt elimination goal (debt-free date, snowball, or avalanche method).\n2. Enter your debts with balances, interest rates, and minimum payments.\n3. Set your monthly cash flow available for extra payments.\n4. Add a motivational dream to keep you inspired.\n\n**Dashboard Features:**\n- **Focus Debt** — The debt you''re currently attacking with extra payments.\n- **Ranked Debt List** — All your debts ordered by your chosen strategy.\n- **Payment Logging** — Record payments and track balance changes.\n- **Motivation Card** — Your dream and inspiration images to stay motivated.\n- **Cash Flow Status** — Monitor your monthly payment capacity.\n\nYou can change your focus debt, edit debt details, and log payments at any time.', 8),

('onboarding', '30-Day Onboarding Journey', E'The 30-Day Onboarding Journey is a guided learning experience that introduces you to key financial concepts across all four horsemen.\n\n**Structure:**\n- **Days 1-10 (Clarity Phase):** Build awareness of your financial situation.\n- **Days 11-20 (Action Phase):** Start implementing strategies.\n- **Days 21-30 (Momentum Phase):** Build habits and long-term plans.\n\n**Daily Content:** Each day features a short lesson (3-5 minutes) with:\n- Educational content about a specific topic\n- Quizzes to test your understanding\n- Reflection prompts to personalize your learning\n- Action items linking to relevant app features\n\n**Progress Tracking:** Your streak, completed days, and earned points are tracked automatically. Complete each day to maintain your streak and earn bonus rewards.', 9),

('profile', 'Managing Your Profile', E'Your Profile page lets you view and update all the information you provided during the wizard setup.\n\n**Sections:**\n- **Personal Info** — Name, phone number, and avatar.\n- **Financial Snapshot** — Income, expenses, and cash flow details.\n- **Insurance Coverage** — Health, life, disability, and long-term care status.\n- **Retirement** — Savings balances, contributions, and timeline.\n- **Stress Indicators** — Money worry, emergency confidence, and control feelings.\n\n**Saving Changes:** The profile auto-detects unsaved changes. Use the Save button to persist updates. A confirmation dialog appears if you try to navigate away with unsaved changes.\n\n**Cash Flow Section:** At the bottom, view your calculated monthly cash flow based on income minus expenses.', 10),

('company', 'Company Dashboard', E'The Company Dashboard is available to company administrators and owners.\n\n**Features:**\n- View all team members who joined via your company''s invite link.\n- Track each member''s engagement: streak, tier, points, onboarding status, and assessment completion.\n- Monitor overall team financial wellness metrics.\n\n**Invite Links:** Each company has a unique invite link. Share it with team members so they automatically join your company when they sign up.\n\n**Privacy:** Company admins can see engagement metrics but cannot view individual financial details, assessment answers, or strategy conversations.', 11),

('gamification', 'Points, Badges & Streaks', E'RPRx uses gamification to keep you motivated and engaged.\n\n**Points (XP):** Earn points for completing activities like:\n- Daily check-ins\n- Completing assessments\n- Starting and completing strategies\n- Engaging with the Strategy Assistant\n- Finishing onboarding days\n\n**Tiers:** As you earn points, you progress through tiers:\n- Awakening → Awareness → Action → Acceleration → Mastery\n\n**Badges:** Earn special badges for milestones like completing your first assessment, maintaining a 7-day streak, or finishing the onboarding journey.\n\n**Streaks:** Log in and complete a daily check-in to maintain your streak. Longer streaks earn bonus rewards and unlock achievement badges.\n\n**Leaderboard:** Your tier and points are visible on your dashboard score card, motivating continuous improvement.', 12);
