
-- Seed strategy definitions for all 4 horsemen
INSERT INTO strategy_definitions (id, name, description, horseman_type, difficulty, estimated_impact, sort_order, steps) VALUES
-- Interest strategies
('int_balance_transfer', 'Balance Transfer', 'Transfer high-interest credit card balances to a 0% APR introductory card to eliminate interest charges during the promotional period.', 'interest', 'quick_win', '$500-2,000/year', 1, '["Research 0% APR balance transfer offers", "Compare transfer fees (typically 3-5%)", "Apply for the best card", "Transfer existing balances", "Create payoff plan before promo ends"]'::jsonb),
('int_debt_avalanche', 'Debt Avalanche Method', 'Pay minimums on all debts, then direct extra payments to the highest-interest debt first to minimize total interest paid.', 'interest', 'moderate', '$1,000-5,000/year', 2, '["List all debts with interest rates", "Pay minimums on everything", "Put all extra money toward highest-rate debt", "Once paid off, roll payment to next highest", "Track progress monthly"]'::jsonb),
('int_rate_negotiation', 'Interest Rate Negotiation', 'Call your lenders and negotiate lower interest rates on credit cards and loans using your payment history as leverage.', 'interest', 'quick_win', '$200-1,000/year', 3, '["Gather current rates and payment history", "Research competitor offers", "Call each lender customer service", "Request rate reduction citing loyalty", "Follow up in writing if successful"]'::jsonb),
('int_refinance', 'Loan Refinancing', 'Refinance existing loans at lower rates to reduce monthly payments and total interest over the life of the loan.', 'interest', 'advanced', '$2,000-10,000/year', 4, '["Check your credit score", "Research current market rates", "Get quotes from multiple lenders", "Calculate break-even point", "Complete refinance application"]'::jsonb),
('int_auto_payments', 'Autopay Rate Discounts', 'Enable autopay on loans to receive the 0.25-0.50% interest rate discount many lenders offer.', 'interest', 'quick_win', '$100-500/year', 5, '["List all loans with autopay discounts", "Set up autopay for each qualifying loan", "Confirm rate reduction applied", "Ensure sufficient funds in account", "Monitor first few payments"]'::jsonb),

-- Taxes strategies
('tax_w4_optimize', 'W-4 Withholding Optimization', 'Adjust your W-4 to stop over-withholding taxes, putting more money in each paycheck instead of giving the IRS an interest-free loan.', 'taxes', 'quick_win', '$200-500/month', 6, '["Review last year tax return", "Use IRS withholding estimator", "Complete new W-4 form", "Submit to employer HR", "Verify next paycheck reflects change"]'::jsonb),
('tax_hsa', 'HSA Maximization', 'Open and maximize contributions to a Health Savings Account for triple tax benefits: tax-deductible contributions, tax-free growth, and tax-free withdrawals for medical expenses.', 'taxes', 'moderate', '$1,000-3,000/year', 7, '["Confirm you have an HDHP plan", "Open an HSA account", "Set up automatic contributions", "Keep receipts for medical expenses", "Consider investing excess funds"]'::jsonb),
('tax_retirement_contributions', 'Maximize Retirement Contributions', 'Increase 401(k) or IRA contributions to reduce taxable income while building long-term wealth.', 'taxes', 'moderate', '$1,500-5,000/year', 8, '["Review current contribution rate", "Calculate maximum affordable increase", "Adjust 401k contribution with employer", "Open/fund IRA if eligible", "Consider Roth vs Traditional based on bracket"]'::jsonb),
('tax_deduction_tracking', 'Deduction & Credit Tracking', 'Systematically track all eligible deductions and credits throughout the year instead of scrambling at tax time.', 'taxes', 'quick_win', '$500-2,000/year', 9, '["Set up expense tracking system", "Create categories for deductible expenses", "Save all receipts digitally", "Review quarterly for missed deductions", "Compare standard vs itemized at year end"]'::jsonb),
('tax_dependent_credits', 'Dependent Care Optimization', 'Maximize child tax credits, dependent care FSAs, and education credits available to families.', 'taxes', 'moderate', '$1,000-4,000/year', 10, '["Review all available family tax credits", "Set up dependent care FSA", "Track childcare and education expenses", "Claim child tax credit properly", "Consider education tax credits"]'::jsonb),

-- Insurance strategies
('ins_policy_review', 'Annual Policy Review', 'Review all insurance policies annually to eliminate coverage gaps, reduce overlapping coverage, and ensure competitive rates.', 'insurance', 'quick_win', '$300-1,500/year', 11, '["List all current insurance policies", "Review coverage amounts and deductibles", "Identify overlapping coverage", "Get competing quotes", "Negotiate or switch for better rates"]'::jsonb),
('ins_bundle_discount', 'Multi-Policy Bundling', 'Bundle home, auto, and other insurance policies with one carrier to receive multi-policy discounts of 10-25%.', 'insurance', 'quick_win', '$200-800/year', 12, '["List all separate insurance policies", "Get bundle quotes from 3+ carriers", "Compare total cost vs current separate policies", "Switch if savings exceed 10%", "Review annually for competitiveness"]'::jsonb),
('ins_deductible_optimize', 'Deductible Optimization', 'Raise deductibles on policies where you have sufficient emergency funds to significantly lower premiums.', 'insurance', 'moderate', '$400-1,200/year', 13, '["Review current deductibles on all policies", "Calculate premium savings for higher deductibles", "Ensure emergency fund covers new deductibles", "Adjust deductibles with carriers", "Set aside deductible amount in savings"]'::jsonb),
('ins_life_review', 'Life Insurance Right-Sizing', 'Evaluate whether current life insurance coverage matches actual needs — avoid both under-insurance and expensive over-insurance.', 'insurance', 'moderate', '$200-1,000/year', 14, '["Calculate actual coverage needed (10-12x income)", "Review current policies and coverage", "Compare term vs whole life costs", "Eliminate unnecessary riders", "Shop for competitive term rates"]'::jsonb),
('ins_health_plan_optimize', 'Health Plan Optimization', 'Compare health plan options during open enrollment to find the best value based on your actual usage patterns.', 'insurance', 'moderate', '$500-2,000/year', 15, '["Review last year medical expenses", "Compare available plan options", "Calculate total cost including premiums and OOP", "Consider HSA-eligible high-deductible plans", "Enroll in optimal plan during open enrollment"]'::jsonb),

-- Education strategies
('edu_529_plan', '529 Education Savings', 'Open and fund a 529 plan for tax-advantaged education savings with potential state tax deductions.', 'education', 'moderate', '$500-2,000/year', 16, '["Research your state 529 plan benefits", "Compare in-state vs out-of-state plans", "Open a 529 account", "Set up automatic contributions", "Review investment allocations annually"]'::jsonb),
('edu_fafsa_timing', 'FAFSA Timing Strategy', 'Optimize the timing of your FAFSA filing and income reporting to maximize financial aid eligibility.', 'education', 'advanced', '$2,000-10,000/year', 17, '["Understand FAFSA income lookback period", "Plan income timing around aid years", "File FAFSA as early as possible", "Report assets strategically", "Appeal aid packages when appropriate"]'::jsonb),
('edu_employer_tuition', 'Employer Education Benefits', 'Take advantage of employer tuition reimbursement and education assistance programs (up to $5,250 tax-free).', 'education', 'quick_win', '$1,000-5,250/year', 18, '["Check employer education benefits policy", "Identify qualifying programs or courses", "Submit pre-approval if required", "Complete coursework and maintain grades", "Submit reimbursement documentation"]'::jsonb),
('edu_tax_credits', 'Education Tax Credits', 'Claim American Opportunity Credit (up to $2,500) or Lifetime Learning Credit (up to $2,000) for qualifying education expenses.', 'education', 'quick_win', '$1,000-2,500/year', 19, '["Determine credit eligibility", "Track qualifying education expenses", "Obtain Form 1098-T from institution", "Claim credit on tax return", "Keep documentation for 3+ years"]'::jsonb),
('edu_scholarship_strategy', 'Scholarship & Grant Strategy', 'Develop a systematic approach to finding and applying for scholarships and grants to reduce education costs.', 'education', 'moderate', '$1,000-5,000/year', 20, '["Create scholarship search profile", "Use multiple scholarship databases", "Apply to 10+ scholarships per quarter", "Write reusable application essays", "Track deadlines and follow up"]'::jsonb);
