// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://wkzgjvnpnhyluxvclymh.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Indremdqdm5wbmh5bHV4dmNseW1oIiwicm9sZSI6ImFub24iLCJpYXQiOjE3Njk1NDc2NjgsImV4cCI6MjA4NTEyMzY2OH0.9JmSBLj8M4TSqvh1x4MPGoq5aiETO3z0xwhep0PfAow";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});